### ISSUE TITLE
Scalar-Vector Multiplication causing segmentation fault.

### ISSUE THREAD

**Issue by naweewan** [gelever/linalgcpp#11]
I added a simple test of scalar-Vector products to the "test_vector" function in test.cpp.  Here is what I added:

    int alpha = 3;
    double beta = 5.1;
    
    v3 *= alpha;
    
    std::cout << "v3 *= 3: " << v3 << "\n";
    
    std::cout << "v3 * 3: " << v3*alpha << "\n";
    
    std::cout << "7 * v3: " << (alpha+4)*v3 << "\n";
    
    std::cout << "5.1*v3" << beta*v3 << "\n";

v*=3 printed out, but then I get a "segmentation fault" error resulting from a bad access.  I'm not sure why however.

**Comment by gelever** [comment]
@naweewan thanks for finding this!  It segfaults because of a bug in swapping Vectors. I'll add more comprehensive tests in the near future that cover all the functions.  

Should be fixed in #12.

If you run into any more problems please let me know :D
